spring.datasource.url=jdbc:sqlite:../cozi.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

cozi.jwt.secret=ReplaceThisSecretKeyForDevOnly
cozi.jwt.expiration-ms=86400000

spring.jackson.serialization.write-dates-as-timestamps=false
server.error.include-message=always
